# Generated by Django 5.0.1 on 2024-03-25 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9006ecb-6ce6-45aa-8b95-ae0510efc3ac'), primary_key=True, serialize=False, unique=True),
        ),
    ]
