# Generated by Django 5.0.1 on 2024-03-25 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_level_user_school_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7751e85-f387-4458-aec1-842b0553b9e3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
