# Generated by Django 5.0.1 on 2024-03-25 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dabdece5-958f-4427-8bbd-57fa0974dbd2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
