# Generated by Django 5.0.1 on 2024-03-26 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecd0ceef-1c0d-4eb1-a319-9fbd33924aa6'), primary_key=True, serialize=False, unique=True),
        ),
    ]
