# Generated by Django 5.0.1 on 2024-03-26 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('883b24c7-57ce-473f-b98a-bd703830c976'), primary_key=True, serialize=False, unique=True),
        ),
    ]
