# Generated by Django 5.0.1 on 2024-04-01 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f78b168-2195-4931-9510-4858a6a9b7fd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
