# Generated by Django 5.0.1 on 2024-04-01 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_id_guestuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestuser',
            old_name='sesson_key',
            new_name='session_key',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c78db8b-8d20-464b-b4a4-bf33154f14b4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
