# Generated by Django 5.0.1 on 2024-04-12 04:17

import apps.accounts.models
import autoslug.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_display_name_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from=apps.accounts.models.slugify_display_name, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93a03417-4c11-4a17-b82d-35221b7d63bc'), primary_key=True, serialize=False, unique=True),
        ),
    ]
