# Generated by Django 5.0.1 on 2024-03-26 22:41

import apps.course_materials.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(storage=apps.course_materials.customs.CustomGoogleDriveStorage(), upload_to='materials/'),
        ),
    ]
